version: 1

project_name: ethr-cli

env_files:
    github_token: ~/.config/goreleaser/github_token

before:
    hooks:
        - go vet
        - go mod tidy
        - go mod vendor
        - go generate ./...

builds:
    -   env:
            - CGO_ENABLED=0
        goos:
            - linux
            - windows
            - darwin

archives:
    -   format: tar.gz
        name_template: >-
            {{ .ProjectName }}-
            {{- .Os }}-
            {{- if eq .Arch "amd64" }}x86-64
            {{- else if eq .Arch "386" }}i386
            {{- else }}{{ .Arch }}{{ end }}
            {{- if .Arm }}v{{ .Arm }}{{ end }}
        format_overrides:
            -   goos: windows
                format: zip

# gitlab_urls:
#     api: https://gitlab.com/api/v4/
#     download: https://gitlab.com
#     skip_tls_verify: false
#     use_package_registry: true
#     use_job_token: true

brews:
    -   name: ethr-cli

        # url_template: "git@gitlab.com:ethrgg/templates/ethr-cli.git"

        commit_author:
            name: Jacob B. Sanders
            email: segmentational@gmail.com

        commit_msg_template: "[Chore]: Brew Formula Bump ({{ .ProjectName }}), {{ .Tag }}"

        folder: Formula

        # caveats: |
        #     Internal Usage Only

        homepage: "https://github.com/x-ethr/ethr-cli" # "https://gitlab.com/ethrgg/templates/ethr-cli"

        description: "ETHR Utilities CLI"

        license: "BSD 3-Clause License"

        skip_upload: false # true

        download_strategy: CurlDownloadStrategy # GitDownloadStrategy

        dependencies:
            -   name: git
                os: mac
            # -   name: go
            #     version: "1.22"
            #     type: build
            -   name: zsh
                type: optional
            -   name: fish
                type: optional
            -   name: bash
                type: optional

        conflicts:
            - ethr-cli

        # --> required gitlab configuration
        # install: | # https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md
        #     ENV["GOPATH"] = buildpath
        #     # bin_path = buildpath/"src/gitlab.com:ethrgg/templates/ethr-cli"
        #     bin_path = buildpath/"src/gitlab.com:ethrgg/templates/ethr-cli"
        #     bin_path.install Dir["*"]
        #     cd bin_path do
        #         system "go", "build", "-o", bin/"ethr-cli", "."
        #     end

        repository:
            branch: main
            owner: x-ethr
            name: homebrew-taps

changelog:
    use: github # gitlab

    sort: asc

    abbrev: 0

    groups:
        -   title: "Features"
            regexp: '^.*?(f|F)eature(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
            order: 0
        -   title: "Enhancements"
            regexp: '^.*?(e|E)nhancement(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
            order: 1
        -   title: "Bug Fixes"
            regexp: '^.*?(b|B)ug(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
            order: 2
        -   title: "Rollback"
            regexp: '^.*?(r|R)evert(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
            order: 3
        -   title: "Chore"
            regexp: '^.*?(c|C)hore(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
            order: 4
        -   title: "Documentation"
            regexp: '^.*?(d|D)ocumentation(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
            order: 5
        -   title: "CI"
            regexp: '^.*?(c|C)(i|I)(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
            order: 6
        -   title: "Refactor"
            regexp: '^.*?(r|R)efactor(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
            order: 7
        -   title: "Internal"
            regexp: '^.*?(i|I)nternal(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
            order: 8
        -   title: Others
            order: 999

    # filters:
    #     include:
    #       - '^.*?(f|F)eature(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
    #       - '^.*?(e|E)nhancement(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
    #       - '^.*?(b|B)ug(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
    #       - '^.*?(r|R)evert(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
    #       - '^.*?(c|C)hore(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
    #       - '^.*?(d|D)ocumentation(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
    #       - '^.*?(c|C)(i|I)(\([[:word:]]+\))??!?(\ |)?(\:|\-)?(\ |).+$'
